name: Build PDF and Compress Src

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fontist
        uses: fontist/setup-fontist@v2
        with:
          fontist-version: 2.0.1 # It looks like the v2.0.4 is not ready like https://github.com/fontist/setup-fontist/issues/20,so pin to v2.0.1

      - name: Install fonts from manifest
        run: fontist manifest-install --confirm-license manifest.yml

      - name: Create output directory
        run: mkdir -p output

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: ^0.14.0

      - name: Compile Typst document
        run: typst compile exam/main.typ output/exam.pdf --font-path ~/.fontist/fonts

      - name: Compress src
        run: tar -cJf output/source.tar.xz exp practice

      - name: Get current date
        id: date
        run: echo "date=$(TZ='Asia/Shanghai' date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.date.outputs.date }}
          name: Release ${{ steps.date.outputs.date }}
          body: |
            ## Build Information

            This was automatically compiled and released by GitHub Actions on `${{ steps.date.outputs.date }}`.

            - **Commit Hash**: `${{ github.sha }}`
            - **Commit Message**: ${{ github.event.head_commit.message }}

            ### Upstream & Resources

            - **Source Code**: [${{ github.repository }}](https://github.com/${{ github.repository }})
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
